config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'articles#index'

  get 'articles/new', to: 'articles#new', as: :new
  post 'articles', to: 'articles#create'

  get 'articles/:id/edit', to: 'articles#edit', as: :edit
  patch 'articles/:id', to: 'articles#update'

  get 'articles/:id', to: 'articles#show', as: :article

  delete 'articles/:id', to: 'articles#destroy', as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)

    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= simple_form_for(@article) do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>

<%%>

app/views/articles/index.html.erb
<h1>Wikinimous</h1>
<%= link_to "New article", new_path%>

<% @articles.each do |article|%>
  <h2><%= link_to article.title, article_path(article)%></h2>
  <p></p><%=article.content%></p>
  <br>
<%end%>

app/views/articles/new.html.erb
<h1>New article</h1>
<%= simple_form_for(@article) do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.submit %>
<% end %>
<%=link_to "back", root_path%>

app/views/articles/show.html.erb
<%require 'faker'%>
<h1><%= @article.title%></h1>

<p><%=@article.content%></p>

<h2><%= Faker::Science.tool%></h2>

<p><%=Faker::Lorem.sentence(word_count: 25)%></p>

<h2><%= Faker::Science.tool%></h2>

<p><%=Faker::Lorem.sentence(word_count: 25)%></p>

<%= link_to "edit article", edit_path%>
<%= link_to "delete article", destroy_path(@article), method: :delete, data: { confirm: "Are you sure?" }%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>